name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        run: ./gradlew build --exclude-task integration-test:test
      - name: deploy in container
        run: java -jar ./web/web-0.0.1-SNAPSHOT.jar
      - name: Wait for API server health check success
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
        run: |
          timeout=20
          while [[ "$timeout" -gt 0 ]]; do
            if curl --fail http://localhost:8080/api/health; then
              echo "API server health check succeeded"
              exit 0
            else
              echo "API server health check failed, retrying in 1 second"
              sleep 1
              ((timeout--))
            fi
          done
          echo "API server health check failed after 20 seconds"
          exit 1
      - name: integration test
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        run: ./gradlew integration-test:test
      - name: api server stop
        run: lsof -i :8080 | awk '{print $2}' | grep -v PID | xargs kill -5